//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taurus.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Taurus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 DATAEXISTS SELECT * FROM DBVersion
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;
        ///  INSERT INTO SY_Config([ID],[Key],[Value]) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM KQ_Rule
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAheadHrs,RuleAheadMins,
        ///    RuleDeferHrs,Rule [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_DATA_ARG {
            get {
                return ResourceManager.GetString("ACCESS_DATA_ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DATAEXISTS SELECT * FROM DBVersion
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;
        ///  INSERT INTO SY_Config([ID],[Key],[Value]) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM KQ_Rule
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAheadHrs,RuleAheadMins,
        ///    RuleDeferHrs,Rule [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_DATA_CHS {
            get {
                return ResourceManager.GetString("ACCESS_DATA_CHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DATAEXISTS SELECT * FROM DBVersion
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;
        ///  INSERT INTO SY_Config([ID],[Key],[Value]) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM KQ_Rule
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAheadHrs,RuleAheadMins,
        ///    RuleDeferHrs,Rule [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_DATA_CHT {
            get {
                return ResourceManager.GetString("ACCESS_DATA_CHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DATAEXISTS SELECT * FROM DBVersion
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;
        ///  INSERT INTO SY_Config([ID],[Key],[Value]) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM KQ_Rule
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAheadHrs,RuleAheadMins,
        ///    RuleDeferHrs,Rule [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_DATA_DEU {
            get {
                return ResourceManager.GetString("ACCESS_DATA_DEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DATAEXISTS SELECT * FROM DBVersion
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;
        ///  INSERT INTO SY_Config([ID],[Key],[Value]) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM KQ_Rule
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAheadHrs,RuleAheadMins,
        ///    RuleDeferHrs,Rule [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_DATA_ENG {
            get {
                return ResourceManager.GetString("ACCESS_DATA_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DATAEXISTS SELECT * FROM DBVersion
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;
        ///  INSERT INTO SY_Config([ID],[Key],[Value]) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM KQ_Rule
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAheadHrs,RuleAheadMins,
        ///    RuleDeferHrs,Rule [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_DATA_ESN {
            get {
                return ResourceManager.GetString("ACCESS_DATA_ESN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DATAEXISTS SELECT * FROM DBVersion
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;
        ///  INSERT INTO SY_Config([ID],[Key],[Value]) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM KQ_Rule
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAheadHrs,RuleAheadMins,
        ///    RuleDeferHrs,Rule [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_DATA_FRA {
            get {
                return ResourceManager.GetString("ACCESS_DATA_FRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DATAEXISTS SELECT * FROM DBVersion
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;
        ///  INSERT INTO SY_Config([ID],[Key],[Value]) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM KQ_Rule
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAheadHrs,RuleAheadMins,
        ///    RuleDeferHrs,Rule [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_DATA_ITA {
            get {
                return ResourceManager.GetString("ACCESS_DATA_ITA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DATAEXISTS SELECT * FROM DBVersion
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2018-07-06&apos;,&apos;&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;
        ///  INSERT INTO SY_Config([ID],[Key],[Value]) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM KQ_Rule
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAheadHrs,RuleAheadMins,
        ///    RuleDeferHrs,Rule [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_DATA_JPN {
            get {
                return ResourceManager.GetString("ACCESS_DATA_JPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DATAEXISTS SELECT * FROM DBVersion
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;
        ///  INSERT INTO SY_Config([ID],[Key],[Value]) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM KQ_Rule
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAheadHrs,RuleAheadMins,
        ///    RuleDeferHrs,Rule [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_DATA_KOR {
            get {
                return ResourceManager.GetString("ACCESS_DATA_KOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DATAEXISTS SELECT * FROM DBVersion
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;
        ///  INSERT INTO SY_Config([ID],[Key],[Value]) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM KQ_Rule
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAheadHrs,RuleAheadMins,
        ///    RuleDeferHrs,Rule [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_DATA_PTG {
            get {
                return ResourceManager.GetString("ACCESS_DATA_PTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DATAEXISTS SELECT * FROM DBVersion
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;
        ///  INSERT INTO SY_Config([ID],[Key],[Value]) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///GO
        ///
        ///DATAEXISTS SELECT * FROM KQ_Rule
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAheadHrs,RuleAheadMins,
        ///    RuleDeferHrs,Rule [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_DATA_RUS {
            get {
                return ResourceManager.GetString("ACCESS_DATA_RUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE DBVersion
        ///(
        ///  DBVer int NULL,
        ///  DBDate datetime NULL,
        ///  AppVer varchar(50) NULL
        ///)
        ///GO
        ///
        ///CREATE TABLE SY_Config
        ///(
        ///  [ID] varchar(50) NOT NULL,
        ///  [Key] varchar(50) NOT NULL,
        ///  [Value] text NULL,
        ///  CONSTRAINT PK_SY_Config PRIMARY KEY([ID],[Key])
        ///)
        ///GO
        ///
        ///CREATE TABLE SY_Log
        ///(
        ///  OprtTime datetime NULL,
        ///  OprtModule varchar(50) NULL,
        ///  OprtTool varchar(50) NULL,
        ///  OprtDetail text NULL,
        ///  OprtNoName varchar(200) NULL,
        ///  OprtComputerName varchar(200) NULL
        ///)
        ///GO
        ///
        ///CREATE TABLE SY_O [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_001 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE RS_Depart
        ///(
        ///  DepartID varchar(20) NOT NULL,
        ///  DepartName varchar(50) NOT NULL,
        ///  DepartUpID varchar(20) NULL,
        ///  DepartMemo text NULL,
        ///  RuleID varchar(10) NULL,
        ///  CONSTRAINT PK_RS_Depart PRIMARY KEY(DepartID)
        ///)
        ///GO
        ///
        ///CREATE TABLE RS_Emp
        ///(
        ///  EmpNo varchar(20) NOT NULL,
        ///  EmpName varchar(50) NULL,
        ///  EmpSex varchar(10) NULL,
        ///  DepartID varchar(20) NULL,
        ///  EmpHireDate datetime NULL,
        ///  EmpCertNo varchar(50) NULL,
        ///  CardNo10 varchar(10) NULL,
        ///  CardNo81 varchar(8) NULL,
        ///  CardNo82 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_002 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE KQ_KQData
        ///(
        ///  [GUID] varchar(36) NOT NULL,
        ///  EmpNo varchar(20) NULL,
        ///  KQDateTime datetime NOT NULL,
        ///  KQDate datetime NOT NULL,
        ///  KQTime varchar(8) NOT NULL,
        ///  MacSN int NULL,
        ///  IsSignIn bit NULL,
        ///  IsInvalid bit NULL,
        ///  OprtNo varchar(10) NULL,
        ///  OprtDate datetime NULL,
        ///  Remark text NULL,
        ///  CONSTRAINT PK_KQ_KQData PRIMARY KEY([GUID]),
        ///  CONSTRAINT AK_KQ_KQData UNIQUE(EmpNo,KQDateTime)
        ///)
        ///GO
        ///
        ///CREATE TABLE KQ_KQDataPhoto
        ///(
        ///  [GUID] varchar(36) NOT NULL,
        ///  Photo image NULL,        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_003 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE DI_MacInfo
        ///(
        ///  MacSN int NOT NULL,
        ///  MacTypeID int NOT NULL,
        ///  MacTypeName varchar(50) NOT NULL,
        ///  MacConnType varchar(10) NOT NULL,
        ///  MacIP varchar(50) NULL,
        ///  MacPort varchar(10) NULL,
        ///  MacConnPWD varchar(10) NULL,
        ///  MacDesc varchar(100) NULL,
        ///  ParamInfo text NULL,
        ///  CONSTRAINT PK_DI_MacInfo PRIMARY KEY(MacSN)
        ///)
        ///GO
        ///
        ///CREATE TABLE DI_PsssTime
        ///(
        ///  PassTimeID tinyint NOT NULL,
        ///  PassTimeName varchar(50) NULL,
        ///  T1S varchar(5) NULL,
        ///  T1E varchar(5) NULL,
        ///  T2S varchar(5) NU [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_004 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE GZ_Rule
        ///(
        ///  RuleID int NOT NULL,
        ///  RuleMode tinyint NULL,
        ///  RuleName varchar(50) NULL,
        ///  IsFunction bit NULL,
        ///  RuleCash decimal(8,2) NULL,
        ///  RuleFunction varchar(255) NULL,
        ///  VRuleFunction varchar(255) NULL,
        ///  CONSTRAINT PK_GZ_Rule PRIMARY KEY(RuleID)
        ///)
        ///GO
        ///
        ///CREATE TABLE GZ_Item
        ///(
        ///  ItemID int NOT NULL,
        ///  ItemName varchar(50) NULL,
        ///  ItemOut0 int NULL,
        ///  ItemOut1 int NULL,
        ///  ItemOut2 int NULL,
        ///  ItemOut3 int NULL,
        ///  ItemOut4 int NULL,
        ///  ItemOut5 int NULL,
        ///  ItemOut6 int N [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_005 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ALTER TABLE KQ_Shift ADD ShiftCount tinyint NULL
        ///GO
        ///ALTER TABLE RS_Emp ADD IsDimission bit NULL
        ///GO
        ///ALTER TABLE RS_Emp ADD DimissionDate datetime NULL
        ///GO
        ///ALTER TABLE RS_Emp ADD DimissionReason varchar(255) NULL
        ///GO
        ///ALTER TABLE RS_Emp ADD DimissionOprt varchar(10) NULL
        ///GO
        ///ALTER TABLE RS_Emp ADD OprtNo varchar(10) NULL
        ///GO
        ///ALTER TABLE RS_Emp ADD OprtDate datetime NULL
        ///GO
        ///UPDATE RS_Emp SET IsDimission=0 WHERE IsDimission IS NULL
        ///GO
        ///ALTER TABLE DI_MacInfo ADD MacMANAGERS int NULL
        ///GO
        ///ALTER TABLE D [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_006 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_007 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_008 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE VIEW VRS_EmpB
        ///AS
        ///  SELECT a.EmpNo,a.EmpName,a.EmpSex,a.DepartID,b.DepartName,a.EmpHireDate,a.EmpCertNo,a.CardNo10,a.CardNo81,a.CardNo82,a.FingerNo,
        ///    a.FingerPrivilege,a.IsAttend,a.RuleID AS EmpRuleID,a.GZRuleID AS EmpGZRuleID,a.IsDimission,a.DimissionDate,a.DimissionReason,
        ///    a.DimissionOprt,a.OprtNo,a.OprtDate,a.EmpAddress,a.EmpPhoneNo,a.EmpMemo,a.EmpGZ,a.GZRuleID,b.GZRuleID as DepGZRuleID,a.[PassWord] as pwd,
        ///    a.EmpFingerCount,a.EmpFaceCount,a.EmpPWCount,a.EmpCardCount,a.EmpPalmVeinCou [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_009 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE VIEW VSY_Oprt
        ///AS
        ///  SELECT CBool(0) AS SelectCheck,OprtNo,OprtName,OprtDesc,OprtIsSys,OprtLastLoginTime
        ///    FROM SY_Oprt
        ///GO
        ///CREATE VIEW [VDI_Dynamic]
        ///AS
        ///  SELECT CBool(0) AS SelectCheck, a.*, b.EmpName, b.FingerNo, b.DepartID, b.DepartName, b.IsDimission
        ///	FROM DI_Dynamic AS a INNER JOIN VRS_Emp AS b ON a.EmpNo = b.EmpNo;
        ///GO
        /// 的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_010 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE VIEW VKQ_KQData
        ///AS
        ///  SELECT b.EmpNo,b.EmpName,b.DepartID,b.DepartName,a.[GUID],a.IsSignIn,a.IsInvalid,b.CardNo10,b.CardNo81,
        ///    b.CardNo82,a.OprtDate,a.OprtNo,a.Remark,a.MacSN,a.KQDateTime,a.KQDate,a.KQTime,
        ///    (SELECT c.OprtName FROM SY_Oprt c WHERE c.OprtNo=a.OprtNo) AS OprtName,a.VerifyModeName,
        ///    (SELECT d.InOutModeName FROM KQ_KQDataInOutMode d WHERE d.InOutModeID=a.InOutModeID) AS InOutModeName,
        ///    a.Temperature,a.TemperatureAlarm 
        ///    FROM KQ_KQData a
        ///    INNER JOIN VRS_Emp b ON b [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_011 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE VIEW VDI_MacInfo
        ///AS
        ///  SELECT CBool(0) AS SelectCheck,*
        ///    FROM DI_MacInfo
        ///GO
        ///
        ///CREATE VIEW VDI_PowerA
        ///AS
        ///  SELECT CBool(0) AS SelectCheck,a.*,b.EmpName,b.FingerNo,b.DepartID,b.DepartName,
        ///    (SELECT T1.PassTimeName FROM DI_PsssTime T1 WHERE T1.PassTimeID=a.SunID) AS SunNa,
        ///    (SELECT T2.PassTimeName FROM DI_PsssTime T2 WHERE T2.PassTimeID=a.MonID) AS MonNa,
        ///    (SELECT T3.PassTimeName FROM DI_PsssTime T3 WHERE T3.PassTimeID=a.TueID) AS TueNa,
        ///    (SELECT T4.PassTimeName FROM DI_PsssTime [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_012 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE VIEW VGZ_RuleItem
        ///AS
        ///  SELECT a.*,b.EmpGZ
        ///    FROM KQ_KQReportMonth a
        ///    LEFT OUTER JOIN RS_Emp b ON b.EmpNo=a.EmpNo
        ///GO
        ///
        ///CREATE VIEW VGZ_Rule
        ///AS
        ///  SELECT CBool(0) AS SelectCheck,*
        ///    FROM GZ_Rule
        ///GO
        ///
        ///CREATE VIEW VGZ_Item1
        ///AS
        ///  SELECT a.*,
        ///    (SELECT IIF(LEN(i0.RuleName)=0,&apos;&apos;,i0.RuleName+&apos;,&apos;) FROM GZ_Rule i0 WHERE i0.RuleID=a.ItemIn0) AS InX0,
        ///    (SELECT IIF(LEN(i1.RuleName)=0,&apos;&apos;,i1.RuleName+&apos;,&apos;) FROM GZ_Rule i1 WHERE i1.RuleID=a.ItemIn1) AS InX1,
        ///    (SELECT IIF(LEN(i2.RuleName) [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_013 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_014 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_015 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_016 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_017 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_018 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_019 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UPDATE DbVersion SET DbDate=&apos;2020-5-8&apos;
        ///GO
        /// 的本地化字符串。
        /// </summary>
        internal static string ACCESS_UPDATE_020 {
            get {
                return ResourceManager.GetString("ACCESS_UPDATE_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] AccessMDB {
            get {
                object obj = ResourceManager.GetObject("AccessMDB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap AddBtn {
            get {
                object obj = ResourceManager.GetObject("AddBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM DBVersion)
        ///BEGIN
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;)
        ///BEGIN
        ///  INSERT INTO SY_Config([ID],[Key],Value) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM KQ_Rule)
        ///BEGIN
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAhead [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DATA_ARG {
            get {
                return ResourceManager.GetString("DATA_ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM DBVersion)
        ///BEGIN
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;)
        ///BEGIN
        ///  INSERT INTO SY_Config([ID],[Key],Value) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM KQ_Rule)
        ///BEGIN
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAhead [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DATA_CHS {
            get {
                return ResourceManager.GetString("DATA_CHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM DBVersion)
        ///BEGIN
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;)
        ///BEGIN
        ///  INSERT INTO SY_Config([ID],[Key],Value) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM KQ_Rule)
        ///BEGIN
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAhead [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DATA_CHT {
            get {
                return ResourceManager.GetString("DATA_CHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM DBVersion)
        ///BEGIN
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;)
        ///BEGIN
        ///  INSERT INTO SY_Config([ID],[Key],Value) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM KQ_Rule)
        ///BEGIN
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAhead [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DATA_DEU {
            get {
                return ResourceManager.GetString("DATA_DEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM DBVersion)
        ///BEGIN
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;)
        ///BEGIN
        ///  INSERT INTO SY_Config([ID],[Key],Value) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM KQ_Rule)
        ///BEGIN
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAhead [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DATA_ENG {
            get {
                return ResourceManager.GetString("DATA_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM DBVersion)
        ///BEGIN
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;)
        ///BEGIN
        ///  INSERT INTO SY_Config([ID],[Key],Value) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM KQ_Rule)
        ///BEGIN
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAhead [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DATA_ESN {
            get {
                return ResourceManager.GetString("DATA_ESN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM DBVersion)
        ///BEGIN
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;)
        ///BEGIN
        ///  INSERT INTO SY_Config([ID],[Key],Value) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM KQ_Rule)
        ///BEGIN
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAhead [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DATA_FRA {
            get {
                return ResourceManager.GetString("DATA_FRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM DBVersion)
        ///BEGIN
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;)
        ///BEGIN
        ///  INSERT INTO SY_Config([ID],[Key],Value) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM KQ_Rule)
        ///BEGIN
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAhead [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DATA_ITA {
            get {
                return ResourceManager.GetString("DATA_ITA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM DBVersion)
        ///BEGIN
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2018-07-06&apos;,&apos;&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;)
        ///BEGIN
        ///  INSERT INTO SY_Config([ID],[Key],Value) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM KQ_Rule)
        ///BEGIN
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAhead [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DATA_JPN {
            get {
                return ResourceManager.GetString("DATA_JPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM DBVersion)
        ///BEGIN
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;)
        ///BEGIN
        ///  INSERT INTO SY_Config([ID],[Key],Value) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM KQ_Rule)
        ///BEGIN
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAhead [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DATA_KOR {
            get {
                return ResourceManager.GetString("DATA_KOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM DBVersion)
        ///BEGIN
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;)
        ///BEGIN
        ///  INSERT INTO SY_Config([ID],[Key],Value) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM KQ_Rule)
        ///BEGIN
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAhead [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DATA_PTG {
            get {
                return ResourceManager.GetString("DATA_PTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM DBVersion)
        ///BEGIN
        ///  INSERT INTO DBVersion(DBVer,DBDate,AppVer) VALUES(1,&apos;2014-07-01&apos;,&apos;&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM SY_Config WHERE [ID]=&apos;SystemRegister&apos; AND [Key]=&apos;BasicName&apos;)
        ///BEGIN
        ///  INSERT INTO SY_Config([ID],[Key],Value) VALUES(&apos;SystemRegister&apos;,&apos;BasicName&apos;,&apos;355FFB2079&apos;)
        ///END
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM KQ_Rule)
        ///BEGIN
        ///  INSERT INTO KQ_Rule(RuleID,RuleName,RuleLateIgnore,RuleLeaveIgnore,RuleDupLimit,RuleLateLeaveCalHrs,RuleLateHrs,RuleLeaveHrs,RuleAhead [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DATA_RUS {
            get {
                return ResourceManager.GetString("DATA_RUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DBRefresh {
            get {
                object obj = ResourceManager.GetObject("DBRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DeleteBtn {
            get {
                object obj = ResourceManager.GetObject("DeleteBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap EditBtn {
            get {
                object obj = ResourceManager.GetObject("EditBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap EditSelectAll {
            get {
                object obj = ResourceManager.GetObject("EditSelectAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap EditUndo {
            get {
                object obj = ResourceManager.GetObject("EditUndo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap EditUnSelectAll {
            get {
                object obj = ResourceManager.GetObject("EditUnSelectAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ExitSystem {
            get {
                object obj = ResourceManager.GetObject("ExitSystem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FilePrint {
            get {
                object obj = ResourceManager.GetObject("FilePrint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FilePrintPreview {
            get {
                object obj = ResourceManager.GetObject("FilePrintPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FileSave {
            get {
                object obj = ResourceManager.GetObject("FileSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FileSaveAll {
            get {
                object obj = ResourceManager.GetObject("FileSaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap GroupBtn {
            get {
                object obj = ResourceManager.GetObject("GroupBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap HelpAbout {
            get {
                object obj = ResourceManager.GetObject("HelpAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Import {
            get {
                object obj = ResourceManager.GetObject("Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap list {
            get {
                object obj = ResourceManager.GetObject("list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap New {
            get {
                object obj = ResourceManager.GetObject("New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Note {
            get {
                object obj = ResourceManager.GetObject("Note", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SignalLEDBlue {
            get {
                object obj = ResourceManager.GetObject("SignalLEDBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SignalLEDGreen {
            get {
                object obj = ResourceManager.GetObject("SignalLEDGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SignalLEDLtBlue {
            get {
                object obj = ResourceManager.GetObject("SignalLEDLtBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SignalLEDOrange {
            get {
                object obj = ResourceManager.GetObject("SignalLEDOrange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SignalLEDRed {
            get {
                object obj = ResourceManager.GetObject("SignalLEDRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SignalLEDViolet {
            get {
                object obj = ResourceManager.GetObject("SignalLEDViolet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SignalLEDYellow {
            get {
                object obj = ResourceManager.GetObject("SignalLEDYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ToolsHammer {
            get {
                object obj = ResourceManager.GetObject("ToolsHammer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;DBVersion&apos;)
        ///  CREATE TABLE DBVersion
        ///  (
        ///    DBVer int NULL,
        ///    DBDate datetime NULL,
        ///    AppVer varchar(50) NULL
        ///  )
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;SY_Config&apos;)
        ///  CREATE TABLE SY_Config
        ///  (
        ///    ID varchar(50) NOT NULL,
        ///    [Key] varchar(50) NOT NULL,
        ///    Value text NULL,
        ///    CONSTRAINT PK_SY_Config PRIMARY KEY(ID,[Key])
        ///  )
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;SY_Log&apos;)
        ///  CREATE TABLE SY_Log
        ///  ( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_001 {
            get {
                return ResourceManager.GetString("UPDATE_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;RS_Depart&apos;)
        ///  CREATE TABLE RS_Depart
        ///  (
        ///    DepartID varchar(20) NOT NULL,
        ///    DepartName varchar(50) NOT NULL,
        ///    DepartUpID varchar(20) NULL,
        ///    DepartMemo text NULL,
        ///    RuleID varchar(10) NULL,
        ///    CONSTRAINT PK_RS_Depart PRIMARY KEY(DepartID)
        ///  )
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;RS_Emp&apos;)
        ///  CREATE TABLE RS_Emp
        ///  (
        ///    EmpNo varchar(20) NOT NULL,
        ///    EmpName varchar(50) NULL,
        ///    EmpSex varchar(10) NULL,
        ///    Dep [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_002 {
            get {
                return ResourceManager.GetString("UPDATE_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;KQ_KQData&apos;)
        ///  CREATE TABLE KQ_KQData
        ///  (
        ///    GUID varchar(36) NOT NULL,
        ///    EmpNo varchar(20) NULL,
        ///    KQDate datetime NOT NULL,
        ///    KQTime int NOT NULL,
        ///    MacSN int NULL,
        ///    IsSignIn bit NULL,
        ///    IsInvalid bit NULL,
        ///    OprtNo varchar(10) NULL,
        ///    OprtDate datetime NULL,
        ///    Remark text NULL,
        ///    CONSTRAINT PK_KQ_KQData PRIMARY KEY(GUID),
        ///    CONSTRAINT AK_KQ_KQData UNIQUE(EmpNo,KQDate,KQTime)
        ///  )
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM sys [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_003 {
            get {
                return ResourceManager.GetString("UPDATE_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;DI_MacInfo&apos;)
        ///  CREATE TABLE DI_MacInfo
        ///  (
        ///    MacSN int NOT NULL,
        ///    MacTypeID int NOT NULL,
        ///    MacTypeName varchar(50) NOT NULL,
        ///    MacConnType varchar(10) NOT NULL,
        ///    MacIP varchar(50) NULL,
        ///    MacPort varchar(10) NULL,
        ///    MacConnPWD varchar(10) NULL,
        ///    MacDesc varchar(100) NULL,
        ///    ParamInfo text NULL,
        ///    CONSTRAINT PK_DI_MacInfo PRIMARY KEY(MacSN)
        ///  )
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;DI_PsssTime&apos;)
        ///  CRE [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_004 {
            get {
                return ResourceManager.GetString("UPDATE_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;GZ_Rule&apos;)
        ///  CREATE TABLE GZ_Rule
        ///  (
        ///    RuleID int NOT NULL,
        ///    RuleMode tinyint NULL,
        ///    RuleName varchar(50) NULL,
        ///    IsFunction bit NULL,
        ///    RuleCash decimal(8, 2) NULL,
        ///    RuleFunction varchar(255) NULL,
        ///    VRuleFunction varchar(255) NULL,
        ///    CONSTRAINT PK_GZ_Rule PRIMARY KEY(RuleID)
        ///  )
        ///GO
        ///
        ///IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;GZ_Item&apos;)
        ///  CREATE TABLE GZ_Item
        ///  (
        ///    ItemID int NOT NULL,
        ///    ItemName varchar(50)  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_005 {
            get {
                return ResourceManager.GetString("UPDATE_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ALTER TABLE KQ_Shift ADD ShiftCount tinyint NULL
        ///GO
        ///ALTER TABLE RS_Emp ADD IsDimission bit NULL
        ///GO
        ///ALTER TABLE RS_Emp ADD DimissionDate datetime NULL
        ///GO
        ///ALTER TABLE RS_Emp ADD DimissionReason varchar(255) NULL
        ///GO
        ///ALTER TABLE RS_Emp ADD DimissionOprt varchar(10) NULL
        ///GO
        ///ALTER TABLE RS_Emp ADD OprtNo varchar(10) NULL
        ///GO
        ///ALTER TABLE RS_Emp ADD OprtDate datetime NULL
        ///GO
        ///UPDATE RS_Emp SET IsDimission=0 WHERE IsDimission IS NULL
        ///GO
        ///ALTER TABLE DI_MacInfo ADD MacMANAGERS int NULL
        ///GO
        ///ALTER TABLE D [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_006 {
            get {
                return ResourceManager.GetString("UPDATE_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF EXISTS(SELECT * FROM sysobjects WHERE name=&apos;GetNextDeptList&apos;) DROP FUNCTION GetNextDeptList
        ///GO
        ///CREATE FUNCTION dbo.GetNextDeptList(@ID varchar(20))
        ///  RETURNS varchar(8000) WITH ENCRYPTION AS
        ///BEGIN
        ///  DECLARE @name varchar(8000),@NID varchar(20),@tmp varchar(8000)
        ///  SELECT @name=&apos;&apos;,@NID=&apos;&apos;
        ///  DECLARE RecNo CURSOR SCROLL FOR SELECT DepartID FROM RS_Depart WHERE DepartUpID=@ID
        ///  OPEN RecNo
        ///  FETCH FIRST FROM RecNo INTO @NID
        ///  WHILE @@FETCH_STATUS=0
        ///  BEGIN
        ///    SELECT @tmp=dbo.GetNextDeptList(@NID) [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_007 {
            get {
                return ResourceManager.GetString("UPDATE_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF EXISTS(SELECT * FROM sysobjects WHERE name=&apos;GetTimeStr&apos;) DROP FUNCTION GetTimeStr
        ///GO
        ///CREATE FUNCTION GetTimeStr(@IntTime int)
        ///  RETURNS varchar(5) WITH ENCRYPTION AS
        ///BEGIN
        ///  DECLARE @Sec int,@Min int,@Hour int,@S varchar(10),@S1 varchar(2),@S2 varchar(2)
        ///  SET @Sec=ABS(@IntTime)
        ///  SET @Hour=@Sec / 3600
        ///  SET @Sec=@Sec % 3600
        ///  SET @Min=@Sec / 60
        ///  SET @Sec=@Sec % 60
        ///  SET @S1=CAST(@Hour AS varchar(2))
        ///  SET @S2=CAST(@Min AS varchar(2))
        ///  WHILE LEN(@S1)&lt;2 SET @S1=&apos;0&apos;+@S1
        ///  WHILE LEN(@S2)&lt;2 S [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_008 {
            get {
                return ResourceManager.GetString("UPDATE_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VRS_EmpA&apos;) DROP VIEW VRS_EmpA
        ///GO
        ///CREATE VIEW VRS_EmpA WITH ENCRYPTION
        ///AS
        ///  SELECT a.EmpNo,a.EmpName,a.EmpSex,a.DepartID,b.DepartName,a.EmpHireDate,a.EmpCertNo,a.CardNo10,a.CardNo81,a.CardNo82,a.FingerNo,
        ///    a.FingerPrivilege,a.IsAttend,a.RuleID AS EmpRuleID,a.GZRuleID AS EmpGZRuleID,a.IsDimission,a.DimissionDate,a.DimissionReason,
        ///    a.DimissionOprt,a.OprtNo,a.OprtDate,c.RuleName AS EmpRuleName,a.EmpAddress,a.EmpPhoneNo,a.EmpMemo,a.EmpGZ,a.GZRuleID,
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_009 {
            get {
                return ResourceManager.GetString("UPDATE_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VSY_Oprt&apos;) DROP VIEW VSY_Oprt
        ///GO
        ///CREATE VIEW VSY_Oprt WITH ENCRYPTION
        ///AS
        ///  SELECT CAST(0 AS bit) AS SelectCheck,OprtNo,OprtName,OprtDesc,CAST(OprtIsSys AS bit) AS OprtIsSys,OprtLastLoginTime
        ///    FROM SY_Oprt
        ///GO
        ///IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VDI_Dynamic&apos;) DROP VIEW VDI_Dynamic
        ///GO
        ///CREATE VIEW VDI_Dynamic WITH ENCRYPTION
        ///AS
        ///  SELECT CAST(0 AS bit) AS SelectCheck,a.*,b.EmpName,b.FingerNo,b.DepartID,b.DepartName,b.IsDimission
        ///    FROM  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_010 {
            get {
                return ResourceManager.GetString("UPDATE_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VKQ_KQData&apos;) DROP VIEW VKQ_KQData
        ///GO
        ///CREATE VIEW VKQ_KQData WITH ENCRYPTION
        ///AS
        ///  SELECT b.EmpNo,b.EmpName,b.DepartID,b.DepartName,a.GUID,a.KQDate,dbo.GetTimeStrEx(a.KQTime) AS KQTime,
        ///    a.IsSignIn,a.IsInvalid,b.CardNo10,b.CardNo81,b.CardNo82,a.OprtDate,c.OprtNo,c.OprtName,a.Remark,
        ///    a.MacSN,a.KQDate+&apos; &apos;+dbo.GetTimeStrEx(a.KQTime) AS KQDateTime,a.VerifyModeName,d.InOutModeName,
        ///    a.Temperature,a.TemperatureAlarm 
        ///    FROM KQ_KQData a
        ///    INNER J [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_011 {
            get {
                return ResourceManager.GetString("UPDATE_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VDI_MacInfo&apos;) DROP VIEW VDI_MacInfo
        ///GO
        ///CREATE VIEW VDI_MacInfo WITH ENCRYPTION
        ///AS
        ///  SELECT CAST(0 AS bit) AS SelectCheck,&apos;&apos; AS MacStatus,a.*
        ///    FROM DI_MacInfo a
        ///GO
        ///
        ///IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VDI_Power&apos;) DROP VIEW VDI_Power
        ///GO
        ///CREATE VIEW VDI_Power WITH ENCRYPTION
        ///AS
        ///  SELECT CAST(0 AS bit) AS SelectCheck,a.*,b.EmpName,b.FingerNo,b.DepartID,b.DepartName,c.MacDesc,
        ///    &apos;[&apos;+CAST(a.SunID AS varchar)+&apos;]&apos;+ISNULL((SELECT T1.PassTi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_012 {
            get {
                return ResourceManager.GetString("UPDATE_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VGZ_RuleItem&apos;) DROP VIEW VGZ_RuleItem
        ///GO
        ///CREATE VIEW VGZ_RuleItem WITH ENCRYPTION
        ///AS
        ///  SELECT a.*,b.EmpGZ
        ///    FROM KQ_KQReportMonth a
        ///    LEFT OUTER JOIN RS_Emp b ON b.EmpNo=a.EmpNo
        ///GO
        ///
        ///IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VGZ_Rule&apos;) DROP VIEW VGZ_Rule
        ///GO
        ///CREATE VIEW VGZ_Rule WITH ENCRYPTION
        ///AS
        ///  SELECT CAST(0 AS bit) AS SELECTCheck,*
        ///    FROM GZ_Rule
        ///GO
        ///
        ///IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VGZ_Item1&apos;) DROP VIEW VGZ_Item [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_013 {
            get {
                return ResourceManager.GetString("UPDATE_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF EXISTS(SELECT * FROM sysobjects WHERE name=&apos;PGetMaxIDFromTable&apos;) DROP PROCEDURE PGetMaxIDFromTable
        ///GO
        ///CREATE PROCEDURE PGetMaxIDFromTable(@FieldName varchar(50),@TableName varchar(50)) WITH ENCRYPTION AS
        ///  DECLARE @S varchar(8000)
        /// 
        ///  SELECT @S=&apos;(SELECT IDENTITY (int,1,1) rn,&apos;+@FieldName+&apos;
        ///         INTO #w
        ///         FROM &apos;+@TableName+&apos; WHERE ISNUMERIC(&apos;+@FieldName+&apos;)=1)  (SELECT ISNULL(MIN(b.&apos;+@FieldName+&apos;),0)+1 AS MaxID FROM 
        ///         (SELECT CAST(a.&apos;+@FieldName+&apos; AS bigint) AS &apos;+@FieldName+&apos; FRO [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_014 {
            get {
                return ResourceManager.GetString("UPDATE_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string UPDATE_015 {
            get {
                return ResourceManager.GetString("UPDATE_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;PKQ_KQDataSave&apos;) DROP PROCEDURE PKQ_KQDataSave
        ///GO
        ///CREATE PROCEDURE PKQ_KQDataSave(@CardType tinyint,@CardNo varchar(10),@KQDate datetime,@KQTime int,@MacSN varchar(50),@OprtNo varchar(10),
        ///  @Remark varchar(255),@VerifyModeID int,@VerifyModeName varchar(50),@InOutModeID int,@InOutModeName varchar(50),
        ///  @Temperature varchar(20),@TemperatureAlarm bit) WITH ENCRYPTION AS
        ///  DECLARE @EmpNo varchar(20),@GUID varchar(36)
        ///  IF @Temperature=&apos;0&apos; SET @Temperature= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_016 {
            get {
                return ResourceManager.GetString("UPDATE_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string UPDATE_017 {
            get {
                return ResourceManager.GetString("UPDATE_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;PGZ_CalcRule&apos;) DROP PROCEDURE PGZ_CalcRule
        ///GO
        ///CREATE PROCEDURE PGZ_CalcRule(@EmpNo varchar(20),@Rule varchar(255),@YM varchar(6),@Ret decimal(16,2) output) WITH ENCRYPTION AS
        ///  DECLARE @sql nvarchar(4000)
        ///  DECLARE @sum numeric
        ///
        ///  IF ISNUMERIC(@Rule)&lt;&gt;1
        ///  BEGIN
        ///    SET @sql=&apos;SELECT @sum=&apos;+@Rule+&apos; FROM VGZ_RuleItem WHERE EmpNo=@EmpNo AND KQYM=@YM&apos;
        ///    EXEC sp_EXECutesql @sql,N&apos;@sum numeric out,@Rule varchar(255),@EmpNo varchar(20),@YM varchar(6)&apos;,@sum  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_018 {
            get {
                return ResourceManager.GetString("UPDATE_018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;TR_RS_Emp&apos;) DROP TRIGGER TR_RS_Emp
        ///GO
        ///CREATE TRIGGER TR_RS_Emp ON RS_Emp WITH ENCRYPTION
        ///FOR UPDATE
        ///AS
        ///  DECLARE @EmpNoOld varchar(20),@EmpNoNew varchar(20),@FingerOld bigint,@FingerNew bigint
        ///  SELECT @EmpNoOld=EmpNo,@FingerOld=FingerNo FROM Deleted
        ///  SELECT @EmpNoNew=EmpNo,@FingerNew=FingerNo FROM Inserted
        ///  IF @EmpNoOld&lt;&gt;@EmpNoNew
        ///  BEGIN
        ///    UPDATE KQ_EmpDayOff SET EmpNo=@EmpNoNew WHERE EmpNo=@EmpNoOld
        ///    UPDATE KQ_EmpOtSure SET EmpNo=@EmpNoNew [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UPDATE_019 {
            get {
                return ResourceManager.GetString("UPDATE_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UPDATE DbVersion SET DbDate=&apos;2020-5-8&apos;
        ///GO
        /// 的本地化字符串。
        /// </summary>
        internal static string UPDATE_020 {
            get {
                return ResourceManager.GetString("UPDATE_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ViewZoomIn {
            get {
                object obj = ResourceManager.GetObject("ViewZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ViewZoomOut {
            get {
                object obj = ResourceManager.GetObject("ViewZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
